--- 
engines: 
  duplication: 
    config: 
      languages: 
        - javascript
    enabled: true
  eslint: 
    config: 
      config: test-riko/.eslintrc.json
    enabled: true
exclude_paths: 
  - bin/**/*
ratings: 
  paths: 
    - "**.js"