engines:
  eslint:
    enabled: true
    config:
        config: test-riko/.eslintrc
    checks:
      global-require:
        enabled: false
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- node_modules/
- test-coverage/
- dist/
- vendor/