engines:
  eslint:
    enabled: true
    checks:
      global-require:
        enabled: false
  ratings:
    paths:
    - src/**
    - "**.js"
    - "**.jsx"
  exclude_paths:
  - node_modules/**/*
  - test-coverage/**/*
  - dist/**/*
  - bin/**/*
  - "**/vendor/**/*"