---
engines:
  duplication:
    config:
      languages:
        - javascript
    enabled: true
  eslint:
    channel: eslint-3
    config:
      config: ./test-riko/.eslintrc.yml
    enabled: true
exclude_paths:
  - bin/**/*
ratings:
  paths:
    - "**.js"