engines:
  eslint:
    enabled: true
    checks:
      global-require:
        enabled: false
    config:
      languages:
      - javascript
exclude_paths:
- node_modules/
- test-coverage/
- dist/
- vendor/