engines:
  eslint:
    enabled: true
    config:
        config: test-riko/.eslintrc
    channel: "eslint-2"
    checks:
      global-require:
        enabled: false
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- node_modules/
- test-coverage/
- test-riko/
- dist/
- vendor/