extends: "stylelint-config-standard"
rules:
 "block-no-empty": null
 "color-no-invalid-hex": true
 "declaration-colon-space-after": always
 "max-empty-lines": 2
 "no-eol-whitespace": null
 "no-missing-end-of-source-newline": null
 "declaration-colon-newline-after": null
 "indentation": null