export const SHOULD_INCREMENT = 'SHOULD_INCREMENT';
export const SHOULD_DECREMENT = 'SHOULD_DECREMENT';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const UPDATE_POSTS = 'UPDATE_POSTS';
export const UPDATE_POST_NUMBER = 'UPDATE_POST_NUMBER';